import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
import MenuNavigation from '@/components/MenuNavigation';
import MenuFooter from '@/components/MenuFooter';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ClimaTrack Canada",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider afterSignInUrl="/">
      <html lang="en">
        <body>
          <main>
            <MenuNavigation />
            {children}
          </main>
          <MenuFooter />
        </body>
      </html>
    </ClerkProvider>
  );
}
